[[site]]
name = "mays"

    [site.mosaiq]
    timezone = "Central Daylight Time"
    hostname = "PRDMOSAIQIWVV01.utmsa.local"
    port = 1433
    alias = "MCC Mosaiq SQL Server"

    [site.export-directories]
    escan = 'C:/users/rembishj/Downloads'

[data_methods]
available = ["dicom", "mosaiq"]
default_reference = "mosaiq"
default_evaluation = "mosaiq"

[output]
png_directory = 'C:/users/rembishj/Downloads'

[gamma]
dose_percent_threshold = 2
distance_mm_threshold = 0.5
local_gamma = true
quiet = true
max_gamma = 5
lower_percent_dose_cutoff = 20

[chart_checks]
archive_path = 'P:\Share\AutoCheck\patient_archive.json'
