name: Heroku

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  OnlineApp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install and Run Cypress
        run: |
          yarn
          export CYPRESS_PYMEDPHYS_GUI_URL="https://app.pymedphys.com"
          yarn cypress run
        working-directory: lib/pymedphys/tests/e2e
